# -*- coding: utf-8 -*-

from BuySale import BuySale

stocks = ['F', 
          'GE', 
          'AAL', 
          'DIS', 
          'DAL', 
          'AAPL', 
          'MSFT', 
          'CCL', 
          'GPRO', 
          'ACB', 
          'PLUG', 
          'NCLH',
          'SNAP',
          'BAC',
          'BA',
          'FIT',
          'UAL',
          'MRNA',
          'NIO',
          'UBER',
          'BABA',
          'AMD',
          'FB',
          'CGC',
          'TWTR',
          'RCL',
          'NFLX',
          'CRON',
          'ZNGA',
          'T',
          'KO',
          'AMZN',
          'TSLA',
          'INO',
          'SAVE',
          'APHA',
          'SBUX',
          'LUV',
          'PFE',
          'JBLU',
          'NKLA',
          'MRO',
          'MGM',
          'GNUS',
          'XOM',
          'MFA',
          'GUSH',
          'SPCE',
          'USO',
          'NVDA',
          'AMC']

buysale = BuySale(10000, stocks)
buysale.buy_sell()